name: Build and Test

# Ne zaman çalışsın? (Push veya Pull Request gelince)
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Test ortamı için Environment Variables
    # (GitHub sunucusunda .env dosyası olmadığı için değerleri buraya elle giriyoruz)
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 3012
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: "ben_kediler_kopekleri_bir_de_tavuklari_cok_severim" 
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30


    # Test için geçici PostgreSQL Servisi (Docker Container)
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: fastapi_test 
        ports:
          - 5432:5432
        # Postgres'in tamamen açılmasını bekleme ayarı (Health Check)
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1. Kodları GitHub'dan çek
      - name: Pull git repo
        uses: actions/checkout@v2

      # 2. Python 3.10 kur
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # 3. Kütüphaneleri yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Testleri çalıştır (Pytest)
      - name: Run tests with pytest
        run: |
          pytest -v -s