name: Build and Deploy

on: [push, pull_request]

jobs:
  # --- 1. AŞAMA: TESTLER (BUILD) ---
  build:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 3012
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: "ben_kediler_kopekleri_bir_de_tavuklari_cok_severim"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 3012
          POSTGRES_DB: fastapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Pull git repo
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create test database
        run: |
          python -c "import psycopg2; conn = psycopg2.connect(user='postgres', password='3012', host='localhost', port='5432'); conn.set_isolation_level(0); cur = conn.cursor(); cur.execute('CREATE DATABASE fastapi_test'); cur.close(); conn.close()"

      - name: Run tests with pytest
        run: |
          pytest -v -s

  # --- 2. AŞAMA: CANLIYA ALMA (DEPLOY) ---
  deploy:
    runs-on: ubuntu-latest
    needs: [build]  # <--- KRİTİK NOKTA: Sadece 'build' başarılı olursa çalış
    if: github.ref == 'refs/heads/main' # Sadece 'main' dalına gelince çalış

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/ubuntu/fastapi-sosyal-medya
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            # alembic upgrade head  <-- Veritabanı göçü yapmıyorsan bunu şimdilik kapalı tuttum, hata vermesin.
            sudo systemctl restart fastapi_app