name: Deploy to AWS

on:
  push:
    branches:
      - main  # Sadece main dalına kod gelince çalış

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}            # Sunucu IP adresi (Gizli)
          username: ${{ secrets.PROD_USERNAME }}    # Kullanıcı adı (ubuntu)
          key: ${{ secrets.PROD_SSH_KEY }}          # O meşhur .pem dosyasının içi
          script: |
            cd /home/ubuntu/fastapi-sosyal-medya    # Proje klasörüne gir
            git pull origin main                    # Yeni kodları çek
            source venv/bin/activate                # Sanal ortamı aç
            pip install -r requirements.txt         # Yeni kütüphane varsa yükle
            alembic upgrade head                    # Veritabanını güncelle (opsiyonel)
            sudo systemctl restart fastapi_app      # Uygulamayı yeniden başlat