name: CI/CD Pipeline ðŸš€

on:
  push:
    branches: [ "main" ]  # Sadece main branch'e kod gelince Ã§alÄ±ÅŸÄ±r

jobs:
  # GÃ–REV 1: Kodu Paketle ve Docker Hub'a Yolla
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: KodlarÄ± Ã‡ek (Checkout)
        uses: actions/checkout@v4

      - name: Docker Hub'a GiriÅŸ Yap
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Ä°majÄ±nÄ± OluÅŸtur ve GÃ¶nder (Build & Push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: bedozsylr/fastapi-sosyal-medya:latest

  # GÃ–REV 2: Sunucuya BaÄŸlan ve GÃ¼ncelle (EÄŸer elindeki PROD anahtarlarÄ± doÄŸruysa Ã§alÄ±ÅŸÄ±r)
  deploy:
    needs: build-and-push  # Ã–nce paketleme bitsin, sonra bu baÅŸlasÄ±n
    runs-on: ubuntu-latest
    steps:
      - name: Sunucuya BaÄŸlan ve GÃ¼ncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd ~/docker-app
            docker-compose pull
            docker-compose up -d